version: '3.0'

services:
  splash:
    image: scrapinghub/splash
    ports: 
      - 8050:8050
      - 5023:5023

  scraper:
    build: .
    links: 
      - splash
    command: scrapy crawl douban_film_spider