version: '3.0'

services:
  splash:
    image: scrapinghub/splash
    ports: 
      - 8050:8050
      - 5023:5023

  mongo:
    image: mongo:latest
    container_name: "scraper_mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user"
      - MONGODB_PASS="pass"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  scraper:
    build: .
    links: 
      - splash
      - mongo
    depends_on:
      - mongo
#    ports:
#      - 9527:22
    command: scrapy crawl douban_film_spider